# Dockerfile.dev
FROM node:18

WORKDIR /app

COPY package*.json ./

# PRECISAMOS RODAR O NPM INSTALL 
# DEPOIS DE CORRIGIREM O ERRO DO NPM INSTALL
RUN npm install 

COPY . .

EXPOSE 3000

CMD ["npm", "start"]